// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250127000000_AddValueObjects")]
    partial class AddValueObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Esta migración documenta la integración de Value Objects.
            // El modelo de base de datos no cambia, solo el mapeo en tiempo de ejecución.
            // El snapshot completo se mantiene en ApplicationDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}

