// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260530190448_AddMissingEntityColumns")]
    partial class AddMissingEntityColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_time");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_appointments_agent_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_appointments_client_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_appointments_vehicle_id");

                    b.HasIndex("DealerId", "StartDateTime", "EndDateTime")
                        .HasDatabaseName("ix_appointments_dealer_time_range");

                    b.ToTable("appointments", "public");
                });

            modelBuilder.Entity("Domain.Cars.Attributes.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_marca");

                    b.ToTable("marca", "public");
                });

            modelBuilder.Entity("Domain.Cars.Attributes.Modelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("uuid")
                        .HasColumnName("marca_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_modelo");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("ix_modelo_marca_id");

                    b.ToTable("modelo", "public");
                });

            modelBuilder.Entity("Domain.Cars.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("año");

                    b.Property<int>("CantidadAsientos")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_asientos");

                    b.Property<int>("CantidadPuertas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_puertas");

                    b.Property<string>("CarStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("car_status");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("car_type");

                    b.Property<int>("Cilindrada")
                        .HasColumnType("integer")
                        .HasColumnName("cilindrada");

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fuel_type");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("integer")
                        .HasColumnName("kilometraje");

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("uuid")
                        .HasColumnName("marca_id");

                    b.Property<Guid>("ModeloId")
                        .HasColumnType("uuid")
                        .HasColumnName("modelo_id");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("patente");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("ServiceCar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_car");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cars");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("ix_cars_marca_id");

                    b.HasIndex("ModeloId")
                        .HasDatabaseName("ix_cars_modelo_id");

                    b.HasIndex("Patente")
                        .IsUnique()
                        .HasDatabaseName("ix_cars_patente");

                    b.ToTable("cars", "public");
                });

            modelBuilder.Entity("Domain.Cars.CarImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cover");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id")
                        .HasName("pk_car_images");

                    b.HasIndex("CarId")
                        .IsUnique()
                        .HasDatabaseName("ux_car_images_car_id_is_cover")
                        .HasFilter("is_cover = true");

                    b.HasIndex("CarId", "DisplayOrder")
                        .HasDatabaseName("ix_car_images_car_id_display_order");

                    b.ToTable("car_images", "public");
                });

            modelBuilder.Entity("Domain.Cars.ReconditioningTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_reconditioning_tasks");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_reconditioning_tasks_car_id");

                    b.HasIndex("DealerId")
                        .HasDatabaseName("ix_reconditioning_tasks_dealer_id");

                    b.ToTable("reconditioning_tasks", "public");
                });

            modelBuilder.Entity("Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dni");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("DNI")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_dni");

                    b.ToTable("clients", "public");
                });

            modelBuilder.Entity("Domain.DealerSettings.DealerSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("CustomDomain")
                        .HasColumnType("text")
                        .HasColumnName("custom_domain");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<string>("DealerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dealer_name");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("text")
                        .HasColumnName("facebook_url");

                    b.Property<string>("FooterText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("footer_text");

                    b.Property<string>("HostName")
                        .HasColumnType("text")
                        .HasColumnName("host_name");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("text")
                        .HasColumnName("instagram_url");

                    b.Property<decimal?>("InterestRateTna")
                        .HasColumnType("numeric")
                        .HasColumnName("interest_rate_tna");

                    b.Property<int>("LastAssignedAgentIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_assigned_agent_index");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notifications_enabled");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("primary_color");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("secondary_color");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("text")
                        .HasColumnName("twitter_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dealer_settings");

                    b.HasIndex("DealerId")
                        .IsUnique()
                        .HasDatabaseName("ix_dealer_settings_dealer_id");

                    b.ToTable("dealer_settings", "public");
                });

            modelBuilder.Entity("Domain.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("blob_name");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<string>("DiscrepancyNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("discrepancy_notes");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("OcrRawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ocr_raw_json");

                    b.Property<string>("OcrStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ocr_status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_documents_client_id");

                    b.HasIndex("DealerId")
                        .HasDatabaseName("ix_documents_dealer_id");

                    b.ToTable("documents", "public");
                });

            modelBuilder.Entity("Domain.Financial.Attributes.TransactionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transaction_categories");

                    b.ToTable("transaction_categories", "public");
                });

            modelBuilder.Entity("Domain.Financial.FinancialTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_number");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_transactions_car_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_transactions_client_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_transactions_sale_id");

                    b.ToTable("transactions", "public");
                });

            modelBuilder.Entity("Domain.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_agent_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Nuevo")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasIndex("DealerId", "AssignedAgentId")
                        .HasDatabaseName("ix_leads_dealer_agent");

                    b.HasIndex("DealerId", "Status")
                        .HasDatabaseName("ix_leads_dealer_status");

                    b.ToTable("leads", "public");
                });

            modelBuilder.Entity("Domain.Quotes.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<decimal>("ProposedPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("proposed_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_quotes_car_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_quotes_client_id");

                    b.ToTable("quotes", "public");
                });

            modelBuilder.Entity("Domain.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comments");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contract_number");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("final_price");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sale_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_sales_car_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_sales_client_id");

                    b.ToTable("sales", "public");
                });

            modelBuilder.Entity("Domain.Shared.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("OutboxMessages", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Domain.Users.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_permissions");

                    b.HasIndex("UserId", "Permission")
                        .IsUnique()
                        .HasDatabaseName("ix_user_permissions_user_id_permission");

                    b.ToTable("UserPermissions", "public");
                });

            modelBuilder.Entity("Domain.Appointments.Appointment", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_users_agent_id");

                    b.HasOne("Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_clients_client_id");

                    b.HasOne("Domain.Cars.Car", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_cars_vehicle_id");
                });

            modelBuilder.Entity("Domain.Cars.Attributes.Modelo", b =>
                {
                    b.HasOne("Domain.Cars.Attributes.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modelo_marca_marca_id");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Domain.Cars.Car", b =>
                {
                    b.HasOne("Domain.Cars.Attributes.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cars_marca_marca_id");

                    b.HasOne("Domain.Cars.Attributes.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cars_modelo_modelo_id");

                    b.OwnsOne("Domain.Shared.ValueObjects.Money", "PurchaseCost", b1 =>
                        {
                            b1.Property<Guid>("CarId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("purchase_cost_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("purchase_cost_currency");

                            b1.HasKey("CarId");

                            b1.ToTable("cars", "public");

                            b1.WithOwner()
                                .HasForeignKey("CarId")
                                .HasConstraintName("fk_cars_cars_id");
                        });

                    b.Navigation("Marca");

                    b.Navigation("Modelo");

                    b.Navigation("PurchaseCost");
                });

            modelBuilder.Entity("Domain.Cars.CarImage", b =>
                {
                    b.HasOne("Domain.Cars.Car", "Car")
                        .WithMany("Images")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_images_cars_car_id");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Domain.Cars.ReconditioningTask", b =>
                {
                    b.HasOne("Domain.Cars.Car", null)
                        .WithMany("ReconditioningTasks")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reconditioning_tasks_cars_car_id");

                    b.OwnsOne("Domain.Shared.ValueObjects.Money", "Cost", b1 =>
                        {
                            b1.Property<Guid>("ReconditioningTaskId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("cost_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("cost_currency");

                            b1.HasKey("ReconditioningTaskId");

                            b1.ToTable("reconditioning_tasks", "public");

                            b1.WithOwner()
                                .HasForeignKey("ReconditioningTaskId")
                                .HasConstraintName("fk_reconditioning_tasks_reconditioning_tasks_id");
                        });

                    b.Navigation("Cost")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Documents.Document", b =>
                {
                    b.HasOne("Domain.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_clients_client_id");

                    b.OwnsOne("Domain.Documents.OcrExtractedData", "ParsedData", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DocumentNumber")
                                .HasColumnType("text");

                            b1.Property<string>("FullName")
                                .HasColumnType("text");

                            b1.Property<string>("IssueDate")
                                .HasColumnType("text");

                            b1.Property<string>("VehicleIdentifier")
                                .HasColumnType("text");

                            b1.Property<string>("VehicleTitleNumber")
                                .HasColumnType("text");

                            b1.HasKey("DocumentId");

                            b1.ToTable("documents", "public");

                            b1.ToJson("parsed_data");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId")
                                .HasConstraintName("fk_documents_documents_id");
                        });

                    b.Navigation("Client");

                    b.Navigation("ParsedData");
                });

            modelBuilder.Entity("Domain.Financial.FinancialTransaction", b =>
                {
                    b.HasOne("Domain.Cars.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_cars_car_id");

                    b.HasOne("Domain.Financial.Attributes.TransactionCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_transaction_categories_category_id");

                    b.HasOne("Domain.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_clients_client_id");

                    b.HasOne("Domain.Sales.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_sales_sale_id");

                    b.Navigation("Car");

                    b.Navigation("Category");

                    b.Navigation("Client");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Domain.Quotes.Quote", b =>
                {
                    b.HasOne("Domain.Cars.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quotes_cars_car_id");

                    b.HasOne("Domain.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quotes_clients_client_id");

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Sales.Sale", b =>
                {
                    b.HasOne("Domain.Cars.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_cars_car_id");

                    b.HasOne("Domain.Clients.Client", "Client")
                        .WithMany("Sales")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_clients_client_id");

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Users.UserPermission", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Cars.Attributes.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("Domain.Cars.Car", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ReconditioningTasks");
                });

            modelBuilder.Entity("Domain.Clients.Client", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
